services:
  - type: web
    name: crop-climate-backend
    env: node
    rootDir: backend-node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
